set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v142)

#set(VCPKG_TARGET_TRIPLET x64-windows)

#set(VS_PLATFORM_TOOLSET "ClangCL,host=x64")

#if(DEFINED VS_PLATFORM_TOOLSET)
#    set(VCPKG_POLICY_SKIP_ARCHITECTURE_CHECK enabled)
#endif()

#set(TARGET_ARCHITECTURE AMD64)
#set(VS_PLATFORM_TOOLSET_OVERRIDE "Intel C++ Compiler 19.0")
#set(VS_PLATFORM_TOOLSET "Intel C++ Compiler 19.0")
#set(CMAKE_GENERATOR_PLATFORM x64)
#set(CMAKE_HOST_SYSTEM_VERSION "10.0.17134")
#set(CMAKE_HOST_SYSTEM_PROCESSOR "AMD64")
#set(CMAKE_SYSTEM_VERSION "10.0.17134")
#set(CMAKE_SYSTEM_PROCESSOR "AMD64")

#set(CMAKE_HOST_SYSTEM_NAME "Windows")
#set(CMAKE_SYSTEM_NAME "Windows")
##set(VS_PLATFORM_TOOLSET "LLVM_v142,host=x64" #"v142,cuda=10.1,host=x64" #"v142,host=x64,v=14.16#version=14.11
#set(VCPKG_CMAKE_SYSTEM_PROCESSOR AMD64)
#set(VCPKG_TARGET_TRIPLET_ARCH x64)
#set(VCPKG_TARGET_TRIPLET_PLAT "Windows")
#set(CMAKE_SYSTEM_VERSION 10.0.15063)
#set(VCPKG_CMAKE_SYSTEM_VERSION "10.0.17134")
#set(VCPKG_CMAKE_SYSTEM_NAME Windows)
#set(VCPKG_SYSTEM_VERSION "10.0.17134")

#set(VCPKG_FORTRAN_COMPILER Intel) # Flang, GNU, Intel, PGI
#set(VCPKG_FORTRAN_ENABLED ON)
#set(VCPKG_FORTRAN_COMPILER PGI)

#set(VCPKG_FORTRAN_COMPILER Intel)
#set(CMAKE_Fortran_COMPILER_ID "Intel")
#set(CMAKE_Fortran_COMPILER ifort)
#set(VCPKG_FORTRAN_TOOLSET_VERSION 19)

#set(INTEL_VERSIONS 19)
#set(IFORT_COMPILER 19)

#set(NINJA_CAN_BE_USED ON) # Ninja as generator
#set(NINJA_HOST OFF) # Ninja as parallel configurator
#set(ENABLE_PARALLEL OFF)

#if(${CMAKE_Fortran_COMPILER_ID} STREQUAL "Intel")
#...
#endif()

#set(VCPKG_LINKER_SUBSYSTEM Console)
#set(VCPKG_LINKER_SUBSYSTEM_MIN_VERSION 5.01)
#set(VCPKG_PLATFORM_TOOLSET v141_xp)


