# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#
# Builds and runs vcpkg-test.exe for PRs and CIs.
parameters:
- name: 'pool'
  type: object
  default: {}
jobs:
- job: build
  pool: ${{ parameters.pool }}
  steps:
#  - task: printAllVariables@1
#    displayName: 'Print all variables'
  - task: CmdLine@2
    displayName: "Build and Test vcpkg"
    inputs:
      script: |
        :: TRANSITION, get these tools on the VMs next time we roll them
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x86 -host_arch=x86
        call .\bootstrap-vcpkg.bat -disableMetrics
#        set PATH=downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin;downloads\tools\ninja-1.10.0-windows;%PATH%
#        .\vcpkg.exe fetch cmake
#        .\vcpkg.exe fetch ninja
#        rmdir /s /q build.x86.debug > nul 2> nul
#        cmake.exe -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DVCPKG_DEVELOPMENT_WARNINGS=ON -DVCPKG_WARNINGS_AS_ERRORS=ON -DVCPKG_BUILD_FUZZING=ON -B build.x86.debug -S toolsrc
#        ninja.exe -C build.x86.debug
#        build.x86.debug\vcpkg-test.exe
      failOnStderr: true
