### specific branch build
trigger:
  batch: true
  branches:
    include:
    - master
#    - releases/*
#    - azure-pipelines/*
#    - '*'  # must quote since "*" is a YAML reserved character; we want a string
#    exclude:
#    - releases/old*
#      - refs/tags/{tagname}
#    exclude:
#      - refs/tags/{othertagname}

# specific path build
#  paths:
#    include:
#    - docs/*
#    exclude:
#    - docs/README.md

#  tags:
#    include:
#    - v2.*
#    exclude:
#    - v2.0
### A pipeline with no CI trigger
#trigger: none

### Don't run against PRs
#pr: none
pr:
#- master
#- releases/*
  autoCancel: false
  branches:
    include:
    - master/*
#    - releases/*
#    - azure-pipelines/*
# this is being defined in app-ci pipeline

#resources:
#  pipelines:
#  - pipeline: template # Name of the pipeline resource
#    source: vcpkg-template # Name of the triggering pipeline
#    trigger: 
#      branches:
#        include:
#        - releases/*
#        - master
#        - azure-pipelines/*

#  repositories:
#    - repository: vcpkg-template
#      type: git
#      name: vcpkg-template

jobs:
#- template: windows/run-tests.yml
#  parameters:
#    pool:   # this parameter is called `pool`
#      vmImage: 'windows-latest'  # and it's a mapping rather than a string

#- template: windows/azure-pipelines.yml
#  parameters:
#    triplet: x86-windows
#    jobName: x86_windows
#    pool:   # this parameter is called `pool`
#      vmImage: 'windows-latest'  # and it's a mapping rather than a string

- template: windows/azure-pipelines.yml
  parameters:
    triplet: x64-windows
    jobName: x64_windows
    pool:   # this parameter is called `pool`
      vmImage: 'windows-latest'  # and it's a mapping rather than a string

#- template: windows/azure-pipelines.yml
#  parameters:
#    triplet: x64-windows-static
#    jobName: x64_windows_static
#    pool:   # this parameter is called `pool`
#      vmImage: 'windows-latest'  # and it's a mapping rather than a string

#- template: windows/azure-pipelines.yml
#  parameters:
#    triplet: x64-uwp
#    jobName: x64_uwp
#    pool:   # this parameter is called `pool`
#      vmImage: 'windows-latest'  # and it's a mapping rather than a string

#- template: windows/azure-pipelines.yml
#  parameters:
#    triplet: arm64-windows
#    jobName: arm64_windows
#    pool:   # this parameter is called `pool`
#      vmImage: 'windows-latest'  # and it's a mapping rather than a string

#- template: windows/azure-pipelines.yml
#  parameters:
#    triplet: arm-uwp
#    jobName: arm_uwp
#    pool:   # this parameter is called `pool`
#      vmImage: 'windows-latest'  # and it's a mapping rather than a string

#- template: osx/azure-pipelines.yml
#  parameters:
#    pool:   # this parameter is called `pool`
#      vmImage: 'macOS-10.14' # and it's a mapping rather than a string

#- template: linux/azure-pipelines.yml
#  parameters:
#    pool:   # this parameter is called `pool`
#      vmImage: 'ubuntu-18.04' # and it's a mapping rather than a string
