name: workflow-azure-pipelines

on:
  pull_request:
    branches:
    - '*'

jobs:
 deploy-using-azure-pipelines:
  timeout-minutes: 1440
  continue-on-error: false
  name: deploy to staging
  runs-on: windows-latest
  steps:
#    - uses: Azure/pipelines@v1
    - name: 'Trigger an Azure Pipeline to deploy the app to PRODUCTION'
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/pilot-group-0/vcpkg-fork'
        azure-pipeline-name: 'vcpkg-template' # name of the Azure pipeline to be triggered
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
