name: CMake

on:
  pull_request:
    branches:
    - '*'
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        repository: ''
        clean: ''
    - name: Configure & Environment
      run: |
        cmake -E make_directory toolsrc/build
        cmake -S toolsrc -B toolsrc/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall -Wno-unknown-pragmas -Wno-unused-parameter -fPIC"
      # -DCMAKE_CONFIGURATION_TYPES=Debug;Release 
    - name: Build
      working-directory: ${{runner.workspace}}/vcpkg-template/toolsrc/build
      run: cmake --build . --config Release
