name: YASM

on:
  push:
#  pull_request:
#  issues:
#  release:
#    types:
#      - created

jobs:
  build-windows:
    name: build & install yasm
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
        ref: 'c9db6d70a9ab62ce58a1cf123f2007d7a3ccc528'
        submodules: 'recursive'
        repository: 'yasm/yasm'

    - name: yasm build & install
      run: |
        cmake -E make_directory build
        set _CL_="/MT /Z7 /W4 /WX-" 
        cmake -S . -B build -LA -G"Visual Studio 16 2019" -Ax64 -T"host=x64" -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_CONFIGURATION_TYPES="Debug;Release" -DCMAKE_VERBOSE_MAKEFILE=TRUE -DYASM_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX="artifact/yasm"
        cmake.exe --build build --config Release --target install

    - uses: actions/cache@master
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: '${{ github.workspace }}/artifact/yasm'
        # An explicit key for restoring and saving the cache
        key: yasm
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        #restore-keys: # optional
    
    - uses: actions/upload-artifact@master
#      id: get_release_info
      with:
        # Artifact name
        name: 'yasm'
        # A file, directory or wildcard pattern that describes what to upload
        path: '${{ github.workspace }}/artifact/yasm/*'
    - run: |
        cd '${{ github.workspace }}/artifact/yasm'
        tar.exe -zcf yasm.tar.gzip *


#    - name: Load Release URL File from release job
#      uses: actions/download-artifact@master
#      with:
#        name: 'yasm'
#        path: '${{ github.workspace }}/artifact/yasm'
#    - name: Get Release File Name & Upload URL
#      id: get_release_info
#      shell: bash
#      run: |
#        value=`cat yasm/yasm.txt`
#        echo ::set-output name=upload_url::$value
    - name: Create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}-${{github.run_id }}
        release_name: Release ${{ github.sha }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: true

    - name: Upload to Release
      id: upload_release_asset
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: '${{ github.workspace }}/artifact/yasm/yasm.tar.gzip'
        asset_name: 'yasm.tar.gzip'
        asset_content_type: application/gzip
